config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'login' => 'users#login'
  post 'login' => 'users#create_session', as: 'create_session'
  get 'signup' => 'users#signup'
  post 'signup' => 'users#create', as: 'create_user'
  delete 'logout' => 'users#logout'
  get '/decks/:id/round/:id' => 'decks#start_round', as: 'start_round'
  post '/decks/:id/round/:id' => 'decks#submit_answer', as: 'submit_answer'

  resources :decks do
    resources :rounds
  end
  resources :guesses
  resources :sessions

end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
  has_many :guesses
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards
  has_many :rounds
end

app/models/guess.rb
class Guess < ActiveRecord::Base
  belongs_to :round
  belongs_to :card
end

app/models/round.rb
class Round < ActiveRecord::Base
  belongs_to :user
  belongs_to :deck
  has_many :guesses
end

app/models/user.rb
class User < ActiveRecord::Base
  include BCrypt
  has_many :rounds
  has_many :guesses, through: :rounds
  has_many :decks, through: :rounds

  validates :email, presence: true, uniqueness: true
  validates :password, presence: true

  def authenticate(plaintext_password)
    self.password == plaintext_password
  end

  def password
    @password ||= Password.new(password_hash)
  end

  def password=(new_password)
    @password = Password.create(new_password)
    self.password_hash = @password
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/decks_controller.rb
require 'pry'
class DecksController < ApplicationController
  def show
    @deck = Deck.find(params[:id])
    @round = Round.create(user_id: session[:user_id], deck_id: @deck.id)
    session[:guesses] = 0
  end

  def start_round
    if logged_in?
      @deck = Deck.find_by(id: params[:deck_id])
      @round = Round.find_by(id: params[:round_id])
      @guess = Guess.new
    else
      @errors = "Sorry, you must be logged in to play this deck"
      render text: 'sorry'
    end
  end

  def submit_answer
    ## we need :deck_id, :id, :answer
    ## cur_card = helper method
    p params
    @answer = params[:answer]
    @deck = Deck.find_by(id: params[:deck_id])
    @round = Round.find_by(id: params[:id])
    @guess = Guess.create(round_id: @round.id, card_id: @deck.cards[cur_card].id)
      if params[:answer].downcase == @deck.cards[cur_card].answer.downcase
        @guess.update_attributes(correct: true)
      else
        @guess.update_attributes(correct: false)
      end
    session[:guesses] += 1
    if session[:guesses] == @deck.cards.size
      redirect_to "decks/#{@deck.id}/round/#{@round.id}/results"
    else
      redirect_to "decks/#{@deck.id}/round/#{@round.id}"
    end
  end

  def results
    if is_authenticated?
      @deck = Deck.find_by(id: params[:deck_id])
      @round = Round.find_by(id: params[:id])
      @correct = Guess.where(round: @round, correct: true)
      @incorrect = Guess.where(round: @round, correct: false)
      erb :'results/show'
    else
      @errors = "Sorry, you must be logged in to view results."
      render text: ''
    end
  end
end

app/controllers/index.rb
class IndexController < ApplicationController

  def index

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    if !logged_in?
      @user = User.new
    else
      @user = User.find(session[:user_id])
      @decks = Deck.all
    end
  end

  private

  def logged_in?
    !!  session[:user_id]
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  #GET signup
  def signup
    @user = User.new
  end

  #POST signup
  def create
    p params
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
    end
    redirect_to root_path
  end

  #GET login
  def login
    @user = User.new
  end

  #POST login
  def create_session
    @user = User.find_by(email: params[:user][:email])
    if @user && @user.password == params[:user][:password]
      session[:user_id] = @user.id
    end
    redirect_to root_path
  end

  #DELETE logout
  def logout
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def logged_in?
    !!session[:user_id]
    # redirect('/') unless is_authenticated?
  end

  # def is_authenticated?
  #   return !!session[:id]
  # end

  def current_user
    if session[:user_id]
      return User.find(session[:id])
    else
      return nil
    end
  end

  def cur_card
    session[:guesses]
  end

end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/decks/_answer_form.html.erb
<%= form_tag submit_answer_path do  %>
  <%= params %><br/>
  <%= text_field_tag :deck_id, params[:deck_id] %><br/>
  <%= text_field_tag :round_id, params[:round_id] %><br/>
  <%= text_field_tag :answer %><br/><br/>
  <%= submit_tag 'Submit answer', class: 'btn btn-primary btn-lg' %>
<% end %>






  <!-- <form action="/decks/<%= @deck.id %>/round/<%= @round.id %>" method="post">
    <input type="text" name="answer" placeholder="answer" id="answer"/><br><br>
    <button type="submit" class="btn btn-primary btn-lg">Submit Answer</button>
  </form> -->

app/views/decks/_cycle_cards.html.erb
<% if @deck %>
  <% @cur_round = [] %>
  <% @deck.cards.each {|card| @cur_round << card.question } %>
  <h2><%= @cur_round[cur_card] %></h2>
<% end %>

app/views/decks/_result.html.erb
<div class="alert alert-success" role="alert">
  <h2>Number of correct cards:</h2>
  <h3><%= @correct.count %></h3>
</div>
<div class="alert-danger" role="alert">
  <br>
  <h2>Number of incorrect cards:</h2>
  <h3><%= @incorrect.count %></h3><br>
</div>

app/views/decks/_result_of_prev_question.html.erb
<% if cur_card > 0 %>
  <% if @deck.cards[session[:guesses]-1].guesses.last.correct == true %>
    <div class="alert alert-success" role="alert">
      <h3> WELL DONE</h3>
    </div>
  <% else %>
    <div class="alert alert-danger" role="alert">
      <h2> U WRONG </h2>
    </div>
    <div class="alert-info" role="alert">
      <h2>Correct Answer:  <%= @deck.cards[session[:guesses]-1].answer %></h2>
    </div>
  <% end %>
<% end %>

app/views/decks/results.html.erb
<div class="text-center">
  <%= render 'result' %>
  <br>
  <div class="jumbotron">
    <h2><a href="/decks/<%= @deck.id %>">Play again?</a> | | <a href="/decks">Another deck?</a></h2>
  </div>
</div>

app/views/decks/show.html.erb
<div class="text-center">
  <h2>Are you sure you want to play this game?</h2>
  <div class="jumbotron">
    <h2><%= link_to 'Yes', start_round_path({deck_id: @deck.id, round_id: @round.id})%> || <%= link_to 'No', decks_path %></h2>
  </div>
</div>
<!-- <h2><a href="/decks/<%= @deck.id %>/round/<%= @round.id %>">Yes</a> | | <a href="/decks">No</a></h2> -->

app/views/decks/start_round.html.erb
<div class="text-center">
  <%= render 'result_of_prev_question' %>
  <%= render 'cycle_cards' %>
  <br>
  <%= render 'answer_form' %>
</div>

app/views/layouts/_header.html.erb
<% if logged_in? %>
  <%= link_to 'Logout', logout_path, method: :delete %>
<p>THIS IS MY NAV BAR PLACEHOLDER</p>

<% else %>
<p>You should login </p>
<%= link_to 'Login', login_path %>
<%= link_to 'Signup', signup_path %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashcards</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<%= yield %>

</body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
<% if logged_in? %>
 <% @decks.each do |deck| %>
  <%= link_to deck.name, deck_path(deck) %>
 <% end %>
<% end %>

app/views/users/login.html.erb
<h1>LOGIN</h1>
<%= form_for @user, url: create_session_path do |f| %>
  <%= f.label :email %><br/>
  <%= f.text_field :email %><br/>
  <%= f.label :password %><br/>
  <%= f.password_field :password %><br/>
  <%= f.submit 'Login' %>
<% end %>

app/views/users/signup.html.erb
<h1>SIGNUP</h1>
<%= form_for @user, url: create_user_path do |f| %>
  <%= f.label :email %><br/>
  <%= f.text_field :email %><br/>
  <%= f.label :password %><br/>
  <%= f.password_field :password %><br/>
  <%= f.submit 'Signup' %>
<% end %>